# Generated by Django 4.2.3 on 2023-10-26 12:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.image_uoload_course),
        ),
    ]
